const DB_NAME="MobileWorkspaceDB", STORE="files";
let db, activePath="", dirty=false, searchIndex=0, tabs=[], histories=new Map(), theme="dark";
const $=id=>document.getElementById(id);
const norm=p=>String(p||"").replace(/\\/g,"/").split("/").filter(Boolean).join("/");
const base=p=>norm(p).split("/").pop()||"";
const dir=p=>{let a=norm(p).split("/");a.pop();return a.join("/")};
const esc=s=>String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function openDb(){return new Promise((res,rej)=>{let r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:"path"});r.onsuccess=()=>{db=r.result;res()};r.onerror=()=>rej(r.error)})}
function tx(mode,fn){return new Promise((res,rej)=>{let t=db.transaction(STORE,mode),s=t.objectStore(STORE);let out=fn(s);t.oncomplete=()=>res(out);t.onerror=()=>rej(t.error)})}
const getAll=()=>tx("readonly",s=>new Promise((res,rej)=>{let r=s.getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)}));
const getFile=p=>tx("readonly",s=>new Promise((res,rej)=>{let r=s.get(norm(p));r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)}));
const putFile=(path,content)=>tx("readwrite",s=>s.put({path:norm(path),content:String(content??""),updatedAt:Date.now()}));
const delFile=path=>tx("readwrite",s=>s.delete(norm(path)));
function setDirty(v){dirty=!!v;$("saveIndicator").className="save-indicator "+(dirty?"dirty":"clean");$("saveIndicator").textContent=dirty?"●":"○"}
async function renderTree(){
 let files=await getAll();$("itemCount").textContent=`${files.length} file${files.length===1?"":"s"}`;
 const make=container=>{container.innerHTML="";let root={dirs:new Map(),files:[]};for(let f of files){let parts=norm(f.path).split("/"),n=root;parts.forEach((x,i)=>{if(i===parts.length-1)n.files.push(f);else{if(!n.dirs.has(x))n.dirs.set(x,{dirs:new Map(),files:[]});n=n.dirs.get(x)}});function walk(node,parent,prefix){[...node.dirs].sort().forEach(([name,child])=>{let wrap=document.createElement("div"),row=document.createElement("div"),kids=document.createElement("div");row.className="tree-row";row.innerHTML=`<span class="tree-caret">▸</span><span>📁</span><span class="tree-label">${esc(name)}</span>`;kids.className="tree-children hidden";row.onclick=()=>{kids.classList.toggle("hidden");row.querySelector(".tree-caret").textContent=kids.classList.contains("hidden")?"▸":"▾"};wrap.append(row,kids);parent.append(wrap);walk(child,kids,prefix?prefix+"/"+name:name)});node.files.sort((a,b)=>a.path.localeCompare(b.path)).forEach(f=>{let row=document.createElement("div");row.className="tree-row";row.innerHTML=`<span>📄</span><span class="tree-label">${esc(base(f.path))}</span><button class="tree-action">×</button>`;row.onclick=e=>{if(e.target.tagName==="BUTTON"){removePath(f.path);return}openFile(f.path)};parent.append(row)})}walk(root,container,"")};
 make($("desktopFileTree"));make($("fileTree"));
}
async function removePath(path){if(!confirm(`Delete ${path}?`))return;await delFile(path);if(activePath===path)closeFile();await renderTree()}
async function openFile(path){if(dirty&&!confirm("Discard unsaved changes?"))return;let f=await getFile(path);if(!f)return;activePath=path;$("editor").value=f.content||"";$("activeFileLabel").textContent=path;setDirty(false);rememberHistory(path,$("editor").value,true);if(!tabs.includes(path))tabs.push(path);renderTabs();updateEditorMeta();showEditor();closeDrawer()}
function closeFile(){activePath="";$("editor").value="";$("activeFileLabel").textContent="No file selected";setDirty(false);updateEditorMeta()}
async function save(){if(!activePath)return;await putFile(activePath,$("editor").value);setDirty(false);await renderTree()}
function updateEditorMeta(){let e=$("editor"),lines=e.value.split("\n").length;$("lineNumbers").textContent=Array.from({length:Math.max(1,lines)},(_,i)=>i+1).join("\n");$("highlightCode").innerHTML=highlight(e.value);$("breadcrumbBar").textContent=activePath?"Workspace › "+activePath:"Workspace"}
function highlight(s){return esc(s).replace(/(\/\/.*|\/\*[\s\S]*?\*\/)/g,'<span class="tok-comment">$1</span>').replace(/(["'`])(?:\\.|(?!\1)[^\\])*\1/g,'<span class="tok-string">$&</span>').replace(/\b(const|let|var|function|return|if|else|async|await|class|import|export|from|true|false|null|undefined)\b/g,'<span class="tok-keyword">$1</span>')}
function syncScroll(){let e=$("editor"),h=$("highlightLayer"),n=$("lineNumbers");h.scrollTop=e.scrollTop;h.scrollLeft=e.scrollLeft;n.scrollTop=e.scrollTop}
function rememberHistory(path,value,reset=false){if(!path)return;let h=histories.get(path)||{stack:[],i:-1};if(reset){h={stack:[value],i:0}}else if(h.stack[h.i]!==value){h.stack=h.stack.slice(0,h.i+1);h.stack.push(value);h.i=h.stack.length-1;if(h.stack.length>100){h.stack.shift();h.i--}}histories.set(path,h)}
function undoRedo(delta){let h=histories.get(activePath);if(!h)return;let i=Math.max(0,Math.min(h.stack.length-1,h.i+delta));if(i===h.i)return;h.i=i;$("editor").value=h.stack[i];setDirty(true);updateEditorMeta()}
function renderTabs(){$("tabsBar").innerHTML="";tabs.forEach(p=>{let b=document.createElement("button");b.className="editor-tab "+(p===activePath?"active":"");b.textContent=base(p);b.onclick=()=>openFile(p);$("tabsBar").append(b)})}
function showEditor(){$("explorerView").classList.remove("active");$("editorView").classList.add("active")}
function showExplorer(){$("editorView").classList.remove("active");$("explorerView").classList.add("active")}
function openDrawer(){$("mobileDrawer").classList.add("open");$("drawerScrim").classList.remove("hidden")}
function closeDrawer(){$("mobileDrawer").classList.remove("open");$("drawerScrim").classList.add("hidden")}
async function createFile(){let p=norm(prompt("File path:",activePath?dir(activePath)+"/":"")||"");if(!p)return;if(await getFile(p)){alert("Already exists");return}await putFile(p,"");await renderTree();openFile(p)}
async function createFolder(){let p=norm(prompt("Folder name/path:")||"");if(!p)return;let file=p+"/.gitkeep";await putFile(file,"");await renderTree()}
function quickOpen(){let m=$("quickOpenModal");m.classList.remove("hidden");$("quickOpenInput").value="";renderQuick([]);$("quickOpenInput").focus()}
async function renderQuick(files){if(!files.length)files=await getAll();let q=$("quickOpenInput").value.toLowerCase();$("quickOpenResults").innerHTML="";files.filter(f=>f.path.toLowerCase().includes(q)).slice(0,100).forEach(f=>{let b=document.createElement("button");b.className="quick-item";b.textContent=f.path;b.onclick=()=>{mClose();openFile(f.path)};$("quickOpenResults").append(b)})}
const mClose=()=>$("quickOpenModal").classList.add("hidden");
function insertText(t){let e=$("editor"),a=e.selectionStart,b=e.selectionEnd;e.setRangeText(t,a,b,"end");e.focus();e.dispatchEvent(new Event("input"))}
function downloadCurrent(){if(!activePath)return;let blob=new Blob([$("editor").value],{type:"text/plain"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=base(activePath);a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function exportZip(){if(!window.JSZip)return alert("ZIP library unavailable");let z=new JSZip();for(let f of await getAll())z.file(f.path,f.content);let blob=await z.generateAsync({type:"blob"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="workspace.zip";a.click()}
async function importFiles(list){for(let f of [...list]){let path=norm(f.webkitRelativePath||f.name);if(f.name.endsWith(".zip")&&window.JSZip){let z=await JSZip.loadAsync(f);for(let [p,e] of Object.entries(z.files))if(!e.dir)await putFile(p,await e.async("text"))}else await putFile(path,await f.text())}await renderTree()}
async function searchWorkspace(){let q=prompt("Search all files for:");if(!q)return;let out=[];for(let f of await getAll()){let lines=f.content.split("\n");lines.forEach((x,i)=>{if(x.toLowerCase().includes(q.toLowerCase()))out.push({p:f.path,i:i+1,x})})}alert(out.slice(0,100).map(r=>`${r.p}:${r.i}  ${r.x.trim()}`).join("\n")||"No matches")}
function toggleFullscreen(){let a=$("appContainer"),on=a.classList.toggle("fullscreen");document.body.classList.toggle("editor-is-fullscreen",on);if(on)showEditor()}
async function githubPull(){let token=$("tokenInput").value,repo=$("repoInput").value.trim(),branch=$("branchInput").value.trim()||"main";if(!token||!repo)return alert("Enter token and owner/repository");let r=await fetch(`https://api.github.com/repos/${repo}/git/trees/${branch}?recursive=1`,{headers:{Authorization:`Bearer ${token}`,Accept:"application/vnd.github+json"}});if(!r.ok)return alert("GitHub pull failed: "+r.status);let tree=(await r.json()).tree||[];for(let x of tree.filter(x=>x.type==="blob")){let b=await fetch(x.url,{headers:{Authorization:`Bearer ${token}`}});let j=await b.json();await putFile(x.path,atob(j.content.replace(/\n/g,"")))}await renderTree();alert("Pulled workspace")}
async function githubPush(){await save();let token=$("tokenInput").value,repo=$("repoInput").value.trim(),branch=$("branchInput").value.trim()||"main";if(!token||!repo)return alert("Enter token and owner/repository");let msg=prompt("Commit message:","Update mobile workspace")||"Update mobile workspace";for(let f of await getAll()){let url=`https://api.github.com/repos/${repo}/contents/${encodeURIComponent(f.path).replace(/%2F/g,"/")}`;let h={Authorization:`Bearer ${token}`,Accept:"application/vnd.github+json"};let old=await fetch(url+"?ref="+encodeURIComponent(branch),{headers:h});let body={message:msg,content:btoa(unescape(encodeURIComponent(f.content))),branch};if(old.ok)body.sha=(await old.json()).sha;let r=await fetch(url,{method:"PUT",headers:{...h,"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok)return alert(`Push failed for ${f.path}: ${r.status}`)}alert("Commit & push complete")}
function bind(){
 $("editor").addEventListener("input",()=>{setDirty(true);updateEditorMeta();rememberHistory(activePath,$("editor").value)});
 $("editor").addEventListener("scroll",syncScroll);$("editor").addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key==="s"){e.preventDefault();save()}if((e.ctrlKey||e.metaKey)&&e.key==="p"){e.preventDefault();quickOpen()}if((e.ctrlKey||e.metaKey)&&e.key==="z"){e.preventDefault();undoRedo(e.shiftKey?1:-1)}if((e.ctrlKey||e.metaKey)&&e.key==="y"){e.preventDefault();undoRedo(1)}if((e.ctrlKey||e.metaKey)&&e.key==="g"){e.preventDefault();let n=+prompt("Go to line:");if(n){let lines=$("editor").value.split("\n"),pos=lines.slice(0,n-1).join("\n").length+(n>1?1:0);e.target.setSelectionRange(pos,pos);e.target.focus()}}});
 $("saveLocalBtn").onclick=save;$("closeFileBtn").onclick=closeFile;$("undoBtn").onclick=()=>undoRedo(-1);$("redoBtn").onclick=()=>undoRedo(1);$("quickOpenBtn").onclick=quickOpen;$("jumpLineBtn").onclick=()=>{let n=+prompt("Go to line:");if(n){let e=$("editor"),pos=e.value.split("\n").slice(0,n-1).join("\n").length+(n>1?1:0);e.setSelectionRange(pos,pos);e.focus()}};$("searchToggleBtn").onclick=()=>$("searchReplaceBar").classList.toggle("hidden");
 $("findNextBtn").onclick=()=>{let e=$("editor"),q=$("searchInput").value;if(!q)return;let i=e.value.indexOf(q,searchIndex);if(i<0)i=e.value.indexOf(q,0);if(i>=0){e.focus();e.setSelectionRange(i,i+q.length);searchIndex=i+q.length}};$("replaceBtn").onclick=()=>{let e=$("editor"),q=$("searchInput").value;if(e.selectionStart!==e.selectionEnd&&e.value.slice(e.selectionStart,e.selectionEnd)===q)insertText($("replaceInput").value)};$("replaceAllBtn").onclick=()=>{let q=$("searchInput").value;if(!q)return;$("editor").value=$("editor").value.split(q).join($("replaceInput").value);$("editor").dispatchEvent(new Event("input"))};
 $("newFileBtn").onclick=createFile;$("newFolderBtn").onclick=createFolder;$("openDrawerBtn").onclick=openDrawer;$("closeDrawerBtn").onclick=closeDrawer;$("drawerScrim").onclick=closeDrawer;$("mobileFilesBtn").onclick=openDrawer;$("mobileSearchBtn").onclick=searchWorkspace;$("mobileSaveBtn").onclick=save;$("mobileGitBtn").onclick=githubPush;$("mobileMoreBtn").onclick=()=>showExplorer();
 $("fullscreenBtn").onclick=toggleFullscreen;$("downloadFileBtn").onclick=downloadCurrent;$("exportWorkspaceBtn").onclick=exportZip;$("searchWorkspaceBtn").onclick=searchWorkspace;$("uploadInput").onchange=e=>importFiles(e.target.files);$("zipInput").onchange=e=>importFiles(e.target.files);$("quickOpenInput").oninput=()=>renderQuick([]);$("closeQuickOpenModal").onclick=mClose;
 $("themeSelect").onchange=e=>{document.body.classList.remove("theme-light","theme-monokai");if(e.target.value!=="dark")document.body.classList.add("theme-"+e.target.value);localStorage.setItem("mwe-theme",e.target.value)};$("pullGitHubBtn").onclick=githubPull;$("pushAllGitHubBtn").onclick=githubPush;
 for(let x of ["{","}","(",")","[","]","<",">","=",";","/",":","'","\"","`","_"]){let b=document.createElement("button");b.textContent=x;b.onclick=()=>insertText(x);$("symbolBar").append(b)}
}
(async()=>{await openDb();let t=localStorage.getItem("mwe-theme")||"dark";$("themeSelect").value=t;$("themeSelect").dispatchEvent(new Event("change"));bind();renderTree()})().catch(e=>alert("Workspace startup failed: "+e.message));